1. Primero cargamos el dataset de iris y creamos unva lista con los nombres de las diferentes clases.

In [10]:
import numpy as np                                         
from sklearn.neural_network import MLPClassifier           
from sklearn.model_selection import train_test_split     

classes = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

iris = np.loadtxt('../practices/data/iris.csv', delimiter=',')
iris[0:5,:]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ]])

2. Ahora Formamos la matriz X que contiene la informacion de las 4 caracteristicas y el vector Y que contiene cada una de sus clases.

In [16]:
X = iris[:, :-1]
Y = iris[:, -1]

In [18]:
X[0:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [19]:
Y[0:5]

array([0., 0., 0., 0., 0.])

3. Dividimos nuestros datos en training y test. Tomamos el 15% para test y el resto para test.

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15, random_state=0)

4. Entrenamos a nuestro modelo haciendo uso de una red neuronal que es un perceptron multicapa. Para este procedimiento utilizamos los datos de training.

In [23]:
model = MLPClassifier(solver='lbfgs', hidden_layer_sizes=20, random_state=1, max_iter=300)
model.fit(X, Y)

MLPClassifier(hidden_layer_sizes=20, max_iter=300, random_state=1,
              solver='lbfgs')

5. Con nuestro modelo listo procedemos a crear una matriz con los nuevos datos de la práctica.

In [26]:
new_flowers = np.array([
    [5.1, 3.5, 1.4, 0.2],
    [6.2, 3.1, 5.3, 1.9],
    [5.1, 3.1, 1.3, 0.2],
    [6.8, 3.3, 4.1, 1.1],
    [5.9, 2.9, 4.6, 1.3]
])
new_flowers

array([[5.1, 3.5, 1.4, 0.2],
       [6.2, 3.1, 5.3, 1.9],
       [5.1, 3.1, 1.3, 0.2],
       [6.8, 3.3, 4.1, 1.1],
       [5.9, 2.9, 4.6, 1.3]])

6. Ahora procedemos a predecir la clase a la que pertenece cada flor en base a sus datos.

In [28]:
predictions = np.uint8(model.predict(new_flowers))
predictions

array([0, 2, 0, 1, 1], dtype=uint8)

7. Como podemos observar nos devuelve el numero de clase a la que pertenece cada flor, ahora lo que hacemos es usar ese numero para mostrar su respectiva etiqueta.

In [29]:
pred_labels = [classes[i] for i in predictions]
pred_labels

['Iris-setosa',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor']